#!/usr/bin/python3
"""File contains class definition of City"""
from sqlalchemy import Column, Integer, String, ForeignKey
from relationship_state import Base, State


class City(State):
    """City class inherits from State class

    Links to MySQL table 'cities'

    Attributes:
        id: column of autogenerated unique integer, can't be NULL, primary key
        name: column of string with max 128 characters, can't be NULL
        state_id: column of integer, can't be NULL, foreign key (states.id)
    """
    __tablename__ = 'cities'
    id = Column(Integer, primary_key=True)
    cityname = Column(String(128))
    state_id = Column(Integer, ForeignKey('states.id'))
